### ISSUE TITLE
Generated code contains compiler error (assignment count mismatch)

### ISSUE THREAD

**Issue by tonyxiao** [go-swagger/go-swagger#1094]
## Problem statement
Go swagger generates invalid code. Specifically, here's an excerpt of generated lines

```
func (o *DeleteResourceSchemaID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, _ := o.Context.RouteInfo(r) // this line causes problems
	var Params = NewDeleteResourceSchemaIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
```

And here's the definition of `RouteInfo` function on `Context` struct from the `github.com/go-openapi/runtime/middleware` package

```
func (c *Context) RouteInfo(request *http.Request) (*MatchedRoute, *http.Request, bool) {
```

As you can see function returns 3 results but generated code only accounts for 2 of them, causing compiler to complain

## Steps to reproduce
```bash
$ swagger generate server -t servers/go
....
$ go get -u -f ./servers/go/...
# github.com/segmentio/schema-service/swagger/servers/go/restapi/operations/resource_schema
servers/go/restapi/operations/resource_schema/delete_resource_schema_id.go:41: assignment count mismatch: 2 = 3
servers/go/restapi/operations/resource_schema/get_resource_schema_id.go:41: assignment count mismatch: 2 = 3
servers/go/restapi/operations/resource_schema/put_resource_schema.go:43: assignment count mismatch: 2 = 3
```

## Environment
swagger version: 0.10.0
swagger commit: 4d1e79b5a98c6f67bbf06923643d5317ed37a058
go version go1.8.1 darwin/amd64
OS:  macOS 10.12.5 (16F73)

**Comment by casualjim** [comment]
can you update your swagger command to what's on master, this is fixed there

**Comment by tonyxiao** [comment]
Confirmed latest master fixes it, thanks and closing!

**Comment by petemyron** [comment]
I cloned the repo, checked out the latest commit explicitly in master (just to be sure, since just cloning the repo and building also didn't work), ran `go build` and `swagger version` still shows the same commit id: 
```
➜  git checkout c2a7c881ef89c08a33a18783b4a5c6f6329a0473
HEAD is now at c2a7c88... replace gorilla/context with net.Context (#1090)
➜  go build
➜  swagger version
version: 0.10.0
commit: 4d1e79b5a98c6f67bbf06923643d5317ed37a058
```

I'm sure I'm doing something wrong since I still get the errors `mismatch` mentioned above. Any hints?

**Comment by petemyron** [comment]
I wound up solving the issue by copying one of the include examples near the line for the respective error, but not sure why my code still isn't generating correctly.

FYI, the code in question is in the ServeHTTP func, needed to add rCtx:
```
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
```

**Comment by casualjim** [comment]
ok can you update your runtime to master too? 

go get -u github.com/go-openapi/runtime

or whatever the vendoring tool equivalen tcommand is.

**Comment by RajdeepSardar** [comment]
Dear All,

I am having similar trouble. Please suggest.

swagger version: 0.12.0
commit: 8135eb6728e43b73489e80f94426e6d387809502

go version go1.8.3 linux/amd64
ubuntu 14.04 LTS

I am using following command

/usr/local/bin/swagger generate server -t gen -f ./spec/swagger.yml --exclude-main -A <AppName> -P <principal>

thanks and regards,
Rajdeep
