### ISSUE TITLE
Invalid recursive type

### ISSUE THREAD

**Issue by mhmxs** [go-swagger/go-swagger#1277]
The generated code doesn't compile because it contains recursive type. Let me explain:
I have an [RdsConfig](https://gist.github.com/mhmxs/63060f19ecfbf7c0d375663629701494#file-cb-api-swagger-json-L6225-L6274) model in my swagger.
```
    "RDSConfig" : {
...
        "properties" : {
          "type" : "array",
          "description" : "custom properties for rds connection",
          "uniqueItems" : true,
          "items" : {
            "$ref" : "#/definitions/RdsConfigProperty"
          }
        },
...
      }
    }
```
The properties are  `RdsConfigProperty` in the JSON as well, and the `go-swagger` generates a type called `RdsConfigProperty`
```
type RdsConfigProperty struct {

	// name
	Name string `json:"name,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}
```
But in `RdsConfig` type at Properties it doesn't use `RdsConfigProperty` struct, it uses `RDSConfig`:
```
// RDSConfig r d s config
// swagger:model RDSConfig
type RDSConfig struct {
...
	// properties
	Properties RDSConfig `json:"properties"`
...
}
```

You can find the whole swagger JSON [here](https://gist.github.com/mhmxs/63060f19ecfbf7c0d375663629701494)

## Environment
swagger version: 0.13.0
go version: go version go1.9.2 darwin/amd64 
OS: macOs High Sierra

**Comment by johanbrandhorst** [comment]
Workaround: manually edit the struct like so:

```go
// RDSConfig r d s config
// swagger:model RDSConfig
type RDSConfig struct {
...
	// properties
	Properties *RDSConfig `json:"properties"`
...
}
```

**Comment by johanbrandhorst** [comment]
This is fixed in master. Present in 0.13 still though.

**Comment by fredbi** [comment]
Tested it and it works (releasing a small PR to prove it).

Note that the cloudbreak.json spec still does not compile properly, because of additionalProperties. This story shall alse be told.

**Comment by mhmxs** [comment]
Thanks @fredbi, Could you please share with me the mentioned issue about the additionalProperties?

**Comment by fredbi** [comment]
Yes I'll open another issue with this.  I tested the full cloudstream spec you gave and removed the offending parts so this particular problem may be demonstrated as solved.
