### ISSUE TITLE
Client parameters don't set body when model is an interface

### ISSUE THREAD

**Issue by jcoyne** [go-swagger/go-swagger#1490]
## Problem statement
I have a model like this:
```go
package models
type Resource interface{}
```

And DepositResourceParams looks like this:
```go
type DepositResourceParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*JSON representation of the resource metadata.
	  Required: true
	  In: body
	*/
	Payload models.Resource
}

...

func (o *DepositResourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
```

I would think that WriteToRequest would put the payload in the request, but it doesn't seem to do so.

## Swagger specification
2.0 

## Environment
swagger version: 0.13.0  
go version: 1.9.3 
OS:   OsX

**Comment by stevecookform3** [comment]
I also seem to be hitting this issue when the model is an enum. e.g.

```
type MyEnum string
...
const (
	// MyEnumCONNECTED captures enum value "CONNECTED"
	MyEnumCONNECTED MyEnum = "CONNECTED"
	// MyEnumDISCONNECTED captures enum value "DISCONNECTED"
	MyEnumDISCONNECTED MyEnum = "DISCONNECTED"
)
...
type PutStateParams struct {
	BodyParam models.MyEnum

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}
...
```
is also missing the SetBodyParam from the WriteToRequest.

Looks like there are some body parameters which are not being identified by this line in the template?
```
  {{ if or .Schema.IsInterface .Schema.IsStream (and .Schema.IsArray .Child) (and .Schema.IsNullable (not .HasDiscriminator)) }}if {{ .ValueExpression }} != nil {
```

**Comment by fredbi** [comment]
Different type, but same cause as #1339

**Comment by fredbi** [comment]
@jcoyne : should be fixed by #1508. Could you please confirm?

**Comment by stevecookform3** [comment]
@fredbi doesnt fix the issue above with enums. Is there a readme somewhere which walks through compiling go-swagger locally? having some dependency/tooling issues when trying to compile master..

**Comment by fredbi** [comment]
@stevecookform3 please open a dedicated issue for your problem, which might not be the same as the one reported by @jcoyne. Also please include your swagger spec (or a minimal spec which reproduces the problem) so it is easier to reproduce the problem and assert it is solved.

Regarding install/compile, there is not much to be said besides go getting the dependencies for your generated code to work (go-openapi packages and a few others). Look in the FAQ on the doc site (http://goswagger.io) or search similar questions in issues (label: "install & setup").

**Comment by casualjim** [comment]
it looks like somebody broke our master compile by not adding the required dependencies to our vendor.
We'll fix it. @stevecookform3 we want the most default go toolchain (go get, go test ./..., etc) to work on go-swagger, thanks for letting us know.
