### ISSUE TITLE
panic,embedded meet anonymous

### ISSUE THREAD

**Issue by guxingxin** [go-swagger/go-swagger#2296]
## Problem statement

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1786f3c]

goroutine 1 [running]:
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromStruct(0xc0005fa9e8, 0xc000542880, 0xc0003811a0, 0xc000478000, 0xc0005fa600, 0xc0002b4140, 0x2)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/schema.go:712 +0xe4c
github.com/go-swagger/go-swagger/codescan.(*schemaBuilder).buildFromType(0xc0005fa9e8, 0x1ac5d40, 0xc0003811a0, 0x1ad8c80, 0xc0002b4420, 0x5e, 0x103669b)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/schema.go:233 +0x929
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).buildFromField(0xc0005fbcc8, 0xc00041e370, 0x1ac5d40, 0xc0003811a0, 0x1ad8c80, 0xc0002b4420, 0xc0005fbad8, 0x203000, 0xc00023b020)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/responses.go:161 +0x965
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).buildFromStruct(0xc0005fbcc8, 0xc000543100, 0xc000381140, 0xc0004409c0, 0xc0005fbad8, 0x6, 0x0)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/responses.go:335 +0x21b2
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).buildFromType(0xc0005fbcc8, 0x1ac5c40, 0xc0003810e0, 0xc0004409c0, 0xc0005fbad8, 0x195e782, 0x10)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/responses.go:230 +0x8a3
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).buildFromStruct(0xc0005fbcc8, 0xc0005430c0, 0xc00023a360, 0xc0004409c0, 0xc0005fbad8, 0xc0005fb970, 0x102d021)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/responses.go:271 +0x2689
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).buildFromType(0xc0005fbcc8, 0x1ac5c40, 0xc00023a330, 0xc0004409c0, 0xc0005fbad8, 0x21, 0xc0005fbc30)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/responses.go:230 +0x8a3
github.com/go-swagger/go-swagger/codescan.(*responseBuilder).Build(0xc0005fbcc8, 0xc00023a930, 0x0, 0x0)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/responses.go:144 +0x24d
github.com/go-swagger/go-swagger/codescan.(*specBuilder).buildRespones(0xc0000c88c0, 0x0, 0x0)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/spec.go:170 +0xef
github.com/go-swagger/go-swagger/codescan.(*specBuilder).Build(0xc0000c88c0, 0xc0003bf340, 0x0, 0xc0000c88c0)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/spec.go:57 +0x71
github.com/go-swagger/go-swagger/codescan.Run(0xc00064c000, 0xc00064c000, 0x0, 0x0)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/codescan/application.go:77 +0x83
github.com/go-swagger/go-swagger/cmd/swagger/commands/generate.(*SpecFile).Execute(0xc0000d46e0, 0xc00007e480, 0x1, 0x1, 0xc0000d46e0, 0x1)
        /Users/codoon/Desktop/1/go-swagger-0.23.0/cmd/swagger/commands/generate/spec_go111.go:57 +0x1d2
github.com/jessevdk/go-flags.(*Parser).ParseArgs(0xc0000c3200, 0xc0000c8010, 0x4, 0x4, 0x0, 0x197f91c, 0x2a, 0x18002e0, 0xc000302570)
        /Users/codoon/work/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:316 +0x8ce
github.com/jessevdk/go-flags.(*Parser).Parse(...)
        /Users/codoon/work/pkg/mod/github.com/jessevdk/go-flags@v1.4.0/parser.go:186
main.main()
        /Users/codoon/Desktop/1/go-swagger-0.23.0/cmd/swagger/swagger.go:145 +0xc2c

```

## Steps to reproduce

```
package include
import "xxxxxxxxxx/include2"
// swagger:parameters DemoArgs
type Args struct {
	Id int `json:"id"`
}

// swagger:response Reply
type Reply struct {
	include2.DemoData
}
```

```
package include2

type DemoData struct {
	MoreData struct {
		Name string `json:"name"`
	} `json:"more_data"`
}

```
panic here!!!

https://github.com/go-swagger/go-swagger/blob/3596b40bedd4f06cc918767098568456d2ec2370/codescan/schema.go#L712

```
//I changed my code just fine
package include2

type MoreData struct {
	Name string `json:"name"`
}
type DemoData struct {
	MoreData
}

or 

package include2

type MoreDataItem struct {
	Name string `json:"name"`
}
type DemoData struct {
	MoreData MoreDataItem `json:"more_data"`
}

```

I found the following:

(s *schemaBuilder) buildXXXXX call multiple times,in pakcage `include2` last time,object s package info is `include`,not match ,so not found。

## Environment
swagger version: v0.23.0  
go version:  go1.12.4 darwin/amd64  
OS:   Darwin guxingxin 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by fredbi** [comment]
@guxingxin  I've tried with current master, using go1.14.4 on linux and the spec shows ok when the import are properly resolved. With invalid import ("xxxx"), I've got an error, but no panic.

```
go version
go version go1.14.4 linux/amd64
```
```
swagger generate spec ./...
{
  "swagger": "2.0",
  "paths": {},
  "responses": {
    "Reply": {
      "schema": {
        "type": "object"
      },
      "headers": {
        "more_data": {}
      }
    }
  }
}
```
I've tried to reproduce your setup:
```
cd fixtures/goparsing/bugs/2296
 find .
.
./include
./include/include.go
./include2
./include2/include2.go
./go.mod
```
```
cat include/include.go
package include

import "github.com/go-swagger/go-swagger/fixtures/goparsing/bugs/2296/include2"

// swagger:parameters DemoArgs
type Args struct {
	Id int `json:"id"`
}

// swagger:response Reply
type Reply struct {
	include2.DemoData
}
```
```
package include2

type DemoData struct {
	MoreData struct {
		Name string `json:"name"`
	} `json:"more_data"`
}
```
```
module github.com/go-swagger/go-swagger/fixtures/goparsing/bugs/2296

replace (
	github.com/go-swagger/go-swagger/fixtures/goparsing/bugs/2296/include => ./include
	github.com/go-swagger/go-swagger/fixtures/goparsing/bugs/2296/include2 => ./include2
)

go 1.14
```

**Comment by fredbi** [comment]
I believe this has been already fixed with commit https://github.com/go-swagger/go-swagger/commit/548768a026b86c7f9836e1c0dc76cbdce3718767
so this should be available with release v0.24.0

Could you please confirm the fix?

**Comment by guxingxin** [comment]
> I believe this has been already fixed with commit [548768a](https://github.com/go-swagger/go-swagger/commit/548768a026b86c7f9836e1c0dc76cbdce3718767)
> so this should be available with release v0.24.0
> 
> Could you please confirm the fix?

@fredbi  release 0.24.0 no panic，but the problem that the following code cannot generate documentation still exists

```
package include

import "xxxxxxx/include2"

// swagger:parameters Args
type Args struct {
	Id int `json:"id"`
}

// swagger:response Reply
type Reply struct {
	include2.DemoData
}
```

```
package include2

type MoreDataST struct {
	//name
	Name string `json:"name"`
}

//demoData
type DemoData struct {
	//id
	Id int64 `json:"id"`
	//could not generate document
	MoreData struct {
		//name
		Name string `json:"name"`
	} `json:"more_data"`
	//moreData2
	DemoData2 MoreDataST `json:"demo_data_2"`
}

```
