### ISSUE TITLE
Build fails with latest go-openapi/errors

### ISSUE THREAD

**Issue by facundomedica** [go-swagger/go-swagger#2315]
On version v0.19.6 of github.com/go-openapi/errors they introduced a breaking change and `errors.Required` now asks for 3 values instead of 2, which is used in BindRequest functions:

```
	if err == io.EOF {
		res = append(res, errors.Required("body", "body")) // this now throws a compile error
	} else {
		res = append(res, errors.NewParseError("body", "body", "", err))
	}
```

**Comment by facundomedica** [comment]
Apparently a bunch of dependencies got updated, had to replace them like this for now:

```
replace github.com/go-openapi/errors v0.19.6 => github.com/go-openapi/errors v0.19.4
replace github.com/go-openapi/validate v0.19.10 => github.com/go-openapi/validate v0.19.8
replace github.com/go-openapi/runtime v0.19.16 => github.com/go-openapi/runtime v0.19.15
```

**Comment by etiennedi** [comment]
Thanks @facundomedica for the workaround, works for me as well.

**Comment by facundomedica** [comment]
There's this PR #2313 waiting to be merged, I think that has the actual fix 😄

**Comment by casualjim** [comment]
I merged the PR now. I'll make a release later

**Comment by v-antech** [comment]
It appears that some of the things were missed, The build still fails for generated `..._parameters.go` files.

**Comment by casualjim** [comment]
I made the release. @v-antech can you submit a new issue with some more context? it's hard for me to see what is failing from your message.

**Comment by vadimivanov-careem** [comment]
Unfortunately, it is still reproducible. 
```
        github.com/go-openapi/errors v0.19.2
	github.com/go-openapi/loads v0.19.4
	github.com/go-openapi/runtime v0.19.4
	github.com/go-openapi/spec v0.19.3
	github.com/go-openapi/strfmt v0.19.3
	github.com/go-openapi/swag v0.19.5
	github.com/go-openapi/validate v0.19.8
```
=>
```
        github.com/go-openapi/errors v0.19.6
	github.com/go-openapi/jsonreference v0.19.4 // indirect
	github.com/go-openapi/loads v0.19.5
	github.com/go-openapi/runtime v0.19.20
	github.com/go-openapi/spec v0.19.9
	github.com/go-openapi/strfmt v0.19.5
	github.com/go-openapi/swag v0.19.9
	github.com/go-openapi/validate v0.19.10
	github.com/go-swagger/go-swagger v0.25.0 // indirect
```

swagger server generation creates errors:
```
api/gen/restapi/operations/matching/match_to_roads_parameters.go:178:25: not enough arguments in call to "github.com/go-openapi/errors".Required
	have (string, string)
	want (string, string, interface {})
```
