### ISSUE TITLE
Responses should support a description

### ISSUE THREAD

**Issue by hlubek** [go-swagger/go-swagger#738]
## Problem statement

The `Responses:` of a `swagger:route` should have support to add a description (which is required by the Swagger specification).

Having a comment on the response type adds a description in the `definitions` but not on the `responses`.

## Swagger specification

See http://swagger.io/specification/#responseObject

## Steps to reproduce

1. Declare a `swagger:route` with `Responses:`
2. No description can be set (just a named response)
3. The `description` property is missing on the `responses` object in the generated JSON

**Comment by clawconduce** [comment]
I was looking at adding this (which would fit right here: https://github.com/go-swagger/go-swagger/blob/master/scan/validators.go#L603) but I changed something that made my responses outputs looks like:

```
          "200": {
            "$ref": "#/responses/pet"
          },
          "500": {
            "$ref": "#/responses/pet"
          }
```

and I believe they were previously outputting the schema as a reference - which I mocked up below: 

```
          "200": {
            "schema": {
              "$ref": "#/responses/pet"
            }
          },
```

Whatever the change was, description is no longer required by the parser at http://editor.swagger.io/#/ .  In fact, when including a description, I get a warning that the field is ignored.

**Comment by clawconduce** [comment]
I also wanted to point out that the reference is url encoded, so spaces turn into `%20`.  I was thinking about parsing value portion of the line based on the first space, so any text after the first space would become the description.  I am not sure what I changed in my comment or build command that stopped outputting schema, but I don't think I understand the problem well enough to code a solution.

**Comment by clawconduce** [comment]
I see what the change was - I had a definition instead of a response and just missed that that changed.

I took a stab at a fix in the PR linked above.

**Comment by casualjim** [comment]
I think this is fixed on master now, please close when confirmed

**Comment by hlubek** [comment]
Hi, thx. for the replies and your work!

I still can't get it working though. Do you have an example how and where the description should go?

**Comment by casualjim** [comment]
in your operation

```
// responses:
//   200: body:someModel and the rest is description
```

**Comment by GlenDC** [comment]
Before closed, the documentation at https://github.com/go-swagger/go-swagger/blob/master/docs/generate/spec/route.md#example should probably be updated to reflect this new feature

**Comment by hlubek** [comment]
Thx, I got it working so the description is added to the responses of the operation when using `body:myNamedResponse`.

I wonder though, why I still need to add a wrapper struct for the response and cannot just use a `swagger:model` annotated struct. It's nothing serious but I could save a struct per response and the `responses` in the generated Swagger JSON would get smaller.

Example:

    type authenticateResponse struct {
    	// ID of the authenticated user
    	// Required: true
    	ID bson.ObjectId `json:"id"`
    	// Authentication token
    	// Required: true
    	Token string `json:"token"`
    }

    // swagger:response authenticateResponse
    type authenticateResponseWrapper struct {
    	// in: body
    	Body authenticateResponse
    }

    // swagger:route POST /login authentication login
    //
    // Login user
    //
    // Logs a user in by creating an authentication token `token` ...
    //
    //     Consumes:
    //     - application/x-www-form-urlencoded
    //
    //     Responses:
    //       200: body:authenticateResponse On login success
    //       401: body:errorMessage Invalid credentials
    func authenticateHandler(w http.ResponseWriter, r *http.Request) {
      // ...
    }

**Comment by hlubek** [comment]
So the question is: is the `body:` prefix needed to split for a description or could you generally do that and thus allow responses with a ref to a response and a description in an operation.

**Comment by GlenDC** [comment]
You can use a model directly by defining your example as follows:
```go
// swagger:model authenticateResponse
type authenticateResponse struct {
	// ID of the authenticated user
	// Required: true
	ID bson.ObjectId `json:"id"`
	// Authentication token
	// Required: true
	Token string `json:"token"`
}
```

You might need to generate the spec using the include models flag: `--scan-models`. This way you can prevent having to use a wrapper struct.

Let me know if this works and if you have any further questions on this topic.

**Comment by hlubek** [comment]
Thanks @GlenDC, I missed the `--scan-models` option when generating the spec. Now it works as I'd expect.
